version: '3.8'

services:
  db:
    image: mysql:8.4.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: turbopass
      MYSQL_DATABASE: turbopass
      MYSQL_USER: turbopass
      MYSQL_PASSWORD: turbopass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  mysql_data:
